### ISSUE TITLE
Problem For Running MPM

### ISSUE THREAD

**Issue by hhucyl** [yuanming-hu/taichi#109]
Sorry, I may ask a stupid question. I found a hard time running your mpm code. I just enter into your /taichi/projects/examples/stimulation/2d/mpm  and run ti elastic,py, I found no result. Could you tell me how to run elastic.py and so on ? I seem to run it but I cannot see the result.

**Comment by yuanming-hu** [comment]
Hi hhucyl, I'm sorry that it is probably broken - let me take a look after the SIGGRAPH deadline.

**Comment by hhucyl** [comment]
Hi， have you fixed the broken 2d file?

**Comment by yuanming-hu** [comment]
Hi, I hope you are still interested. Please check out our brand-new MPM solver: https://github.com/yuanming-hu/taichi_mpm

**Comment by hhucyl** [comment]
thx, I will dig it.
