### ISSUE TITLE
Travis CI & AppVeyor Support

### ISSUE THREAD

**Issue by yuanming-hu** [yuanming-hu/taichi#13]
I'm getting tired testing the environment on all the 3 platforms and I think it's better to have CIs for Taichi. Please let me know it you have any suggestion on this topic or want to help realize it. Thank you. It looks that Travis CI for Linux and Mac OSX and AppVeyor for Windows are suitable choices.

**Comment by IteratorAdvance** [comment]
AppVeyor support added.

**Comment by yuanming-hu** [comment]
TravisCI for Linux added.

**Comment by yuanming-hu** [comment]
TravisCI for OS X added. All done.
