### ISSUE TITLE
MinGW support

### ISSUE THREAD

**Issue by yuanming-hu** [yuanming-hu/taichi#136]
Just need a MinGW pre-compiled `tbb` with a C++ ABI compatible with other parts.

**Comment by squarefk** [comment]
Some notes for compiling tbb:

1. use compiler=gcc
2. use extra_inc=big_iron.inc to build static library
3. use CXXFLAGS="-flifetime-dse=1" to avoid conflict with mingw-w64

**Comment by squarefk** [comment]
MinGW-w64 version: x86_64-7.2.0-posix-seh-rt_v5-rev1

**Comment by yuanming-hu** [comment]
Disabled Embree on MinGW to save some effort. We are moving to a GPU renderer based on NVIDIA OptiX so the CPU rendering part may not be really useful.

**Comment by yuanming-hu** [comment]
Done.
