### ISSUE TITLE
installing issue

### ISSUE THREAD

**Issue by bona00ku** [yuanming-hu/taichi#143]
HI, I have trouble while installing taichi.

$python install.py
at my virtualenv give following error messages.

Do you have any suggestion for this?

----------------------------------------------------------------------------------------------------
[ 11%] Building CXX object CMakeFiles/taichi_core.dir/src/io/image_reader.cpp.o
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:79:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:46,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/hjku/workspace/taichi/include/taichi/common/util.h:17,
                 from /home/hjku/workspace/taichi/include/taichi/math/math.h:8,
                 from /home/hjku/workspace/taichi/src/benchmark/simd.cpp:6:
/usr/lib/gcc/x86_64-linux-gnu/5/include/fmaintrin.h: In function ‘typename std::enable_if<(T:: simd && (taichi::default_instruction_set >= AVX)), T>::type taichi::fused_mul_add(const T&, const T&, const T&) [with T = taichi::VectorND<4, float, (taichi::InstSetExt)2>; typename std::enable_if<(T:: simd && (taichi::default_instruction_set >= AVX)), T>::type = taichi::VectorND<4, float, (taichi::InstSetExt)2>]’:
/usr/lib/gcc/x86_64-linux-gnu/5/include/fmaintrin.h:55:1: error: inlining failed in call to always_inline ‘__m128 _mm_fmadd_ps(__m128, __m128, __m128)’: target specific option mismatch
 _mm_fmadd_ps (__m128 __A, __m128 __B, __m128 __C)
 ^
In file included from /home/hjku/workspace/taichi/include/taichi/math/geometry_util.h:11:0,
                 from /home/hjku/workspace/taichi/include/taichi/math/math.h:9,
                 from /home/hjku/workspace/taichi/src/benchmark/simd.cpp:6:
/home/hjku/workspace/taichi/include/taichi/math/vector.h:853:33: error: called from here
   return T(_mm_fmadd_ps(a, b, c));
                                 ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:79:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:46,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/hjku/workspace/taichi/include/taichi/common/util.h:17,
                 from /home/hjku/workspace/taichi/include/taichi/math/math.h:8,
                 from /home/hjku/workspace/taichi/src/benchmark/simd.cpp:6:
/usr/lib/gcc/x86_64-linux-gnu/5/include/fmaintrin.h:55:1: error: inlining failed in call to always_inline ‘__m128 _mm_fmadd_ps(__m128, __m128, __m128)’: target specific option mismatch
 _mm_fmadd_ps (__m128 __A, __m128 __B, __m128 __C)
 ^
In file included from /home/hjku/workspace/taichi/include/taichi/math/geometry_util.h:11:0,
                 from /home/hjku/workspace/taichi/include/taichi/math/math.h:9,
                 from /home/hjku/workspace/taichi/src/benchmark/simd.cpp:6:
/home/hjku/workspace/taichi/include/taichi/math/vector.h:853:33: error: called from here
   return T(_mm_fmadd_ps(a, b, c));
                                 ^
CMakeFiles/taichi_core.dir/build.make:86: recipe for target 'CMakeFiles/taichi_core.dir/src/benchmark/simd.cpp.o' failed
make[2]: *** [CMakeFiles/taichi_core.dir/src/benchmark/simd.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:79:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:46,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/hjku/workspace/taichi/include/taichi/common/util.h:17,
                 from /home/hjku/workspace/taichi/include/taichi/common/dict.h:17,
                 from /home/hjku/workspace/taichi/include/taichi/common/config.h:1,
                 from /home/hjku/workspace/taichi/include/taichi/common/interface.h:8,
                 from /home/hjku/workspace/taichi/include/taichi/visual/volume_material.h:8,
                 from /home/hjku/workspace/taichi/src/volume_material/volume_material.cpp:6:
/usr/lib/gcc/x86_64-linux-gnu/5/include/fmaintrin.h: In function ‘typename std::enable_if<(T:: simd && (taichi::default_instruction_set >= AVX)), T>::type taichi::fused_mul_add(const T&, const T&, const T&) [with T = taichi::VectorND<4, float, (taichi::InstSetExt)2>; typename std::enable_if<(T:: simd && (taichi::default_instruction_set >= AVX)), T>::type = taichi::VectorND<4, float, (taichi::InstSetExt)2>]’:
/usr/lib/gcc/x86_64-linux-gnu/5/include/fmaintrin.h:55:1: error: inlining failed in call to always_inline ‘__m128 _mm_fmadd_ps(__m128, __m128, __m128)’: target specific option mismatch
 _mm_fmadd_ps (__m128 __A, __m128 __B, __m128 __C)
 ^
In file included from /home/hjku/workspace/taichi/include/taichi/math/geometry_util.h:11:0,
                 from /home/hjku/workspace/taichi/include/taichi/math/math.h:9,
                 from /home/hjku/workspace/taichi/include/taichi/common/dict.h:19,
                 from /home/hjku/workspace/taichi/include/taichi/common/config.h:1,
                 from /home/hjku/workspace/taichi/include/taichi/common/interface.h:8,
                 from /home/hjku/workspace/taichi/include/taichi/visual/volume_material.h:8,
                 from /home/hjku/workspace/taichi/src/volume_material/volume_material.cpp:6:
/home/hjku/workspace/taichi/include/taichi/math/vector.h:853:33: error: called from here
   return T(_mm_fmadd_ps(a, b, c));
                                 ^
In file included from /usr/lib/gcc/x86_64-linux-gnu/5/include/immintrin.h:79:0,
                 from /usr/lib/gcc/x86_64-linux-gnu/5/include/x86intrin.h:46,
                 from /usr/include/x86_64-linux-gnu/c++/5/bits/opt_random.h:33,
                 from /usr/include/c++/5/random:50,
                 from /usr/include/c++/5/bits/stl_algo.h:66,
                 from /usr/include/c++/5/algorithm:62,
                 from /home/hjku/workspace/taichi/include/taichi/common/util.h:17,
                 from /home/hjku/workspace/taichi/include/taichi/common/dict.h:17,
                 from /home/hjku/workspace/taichi/include/taichi/common/config.h:1,
                 from /home/hjku/workspace/taichi/include/taichi/common/interface.h:8,
                 from /home/hjku/workspace/taichi/include/taichi/visual/volume_material.h:8,
                 from /home/hjku/workspace/taichi/src/volume_material/volume_material.cpp:6:
/usr/lib/gcc/x86_64-linux-gnu/5/include/fmaintrin.h:55:1: error: inlining failed in call to always_inline ‘__m128 _mm_fmadd_ps(__m128, __m128, __m128)’: target specific option mismatch
 _mm_fmadd_ps (__m128 __A, __m128 __B, __m128 __C)
 ^
In file included from /home/hjku/workspace/taichi/include/taichi/math/geometry_util.h:11:0,
                 from /home/hjku/workspace/taichi/include/taichi/math/math.h:9,
                 from /home/hjku/workspace/taichi/include/taichi/common/dict.h:19,
                 from /home/hjku/workspace/taichi/include/taichi/common/config.h:1,
                 from /home/hjku/workspace/taichi/include/taichi/common/interface.h:8,
                 from /home/hjku/workspace/taichi/include/taichi/visual/volume_material.h:8,
                 from /home/hjku/workspace/taichi/src/volume_material/volume_material.cpp:6:
/home/hjku/workspace/taichi/include/taichi/math/vector.h:853:33: error: called from here
   return T(_mm_fmadd_ps(a, b, c));
                                 ^
CMakeFiles/taichi_core.dir/build.make:182: recipe for target 'CMakeFiles/taichi_core.dir/src/volume_material/volume_material.cpp.o' failed
make[2]: *** [CMakeFiles/taichi_core.dir/src/volume_material/volume_material.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/taichi_core.dir/all' failed
make[1]: *** [CMakeFiles/taichi_core.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
  Error: Build failed.
  Error: installation failed.
---------------------------------------------------------------------------------------

**Comment by yuanming-hu** [comment]
I tried installing on my Ubuntu 16.04 VM and got the same issue. This can be solved by changing
Line 45-47 in `cmake/TaichiCXXFlags.cmake` from
```
    set(CMAKE_CXX_FLAGS
            "${CMAKE_CXX_FLAGS} -std=c++14 -march=native\
 -DGL_DO_NOT_WARN_IF_MULTI_GL_VERSION_HEADERS_INCLUDED -Wall")
```
to
```
    set(CMAKE_CXX_FLAGS
            "${CMAKE_CXX_FLAGS} -std=c++14 -march=**haswell**\
 -DGL_DO_NOT_WARN_IF_MULTI_GL_VERSION_HEADERS_INCLUDED -Wall")
```

**Comment by bona00ku** [comment]
Hi! Thanks for quick answering!

Yes, I am using virtualenv to use python3 and avoid dependency issues.

CPU : intel core i7-3770, 3.40GHz? x8
GPU : GeForce GTX 1080 Ti


After changing that line, I also got an error.
What is the meaning of 

> **haswell**

 It makes error..
-----------------------------------------------------------------------------------------------------------------------------------
[  8%] Building CXX object CMakeFiles/taichi_core.dir/src/sampler/sampler.cpp.o
/home/hjku/workspace/taichi/src/volume_material/volume_material.cpp:1:0: error: bad value (**haswell**) for -march= switch
 /*******************************************************************************
 ^
/home/hjku/workspace/taichi/src/benchmark/spgrid.cpp:1:0: error: bad value (**haswell**) for -march= switch
 /*******************************************************************************
 ^
/home/hjku/workspace/taichi/src/benchmark/mpm3_details.cpp:1:0: error: bad value (**haswell**) for -march= switch
 /*******************************************************************************
 ^
/home/hjku/workspace/taichi/src/benchmark/simd.cpp:1:0: error: bad value (**haswell**) for -march= switch
 /*******************************************************************************
 ^
/home/hjku/workspace/taichi/src/levelset/sdf.cpp:1:0: error: bad value (**haswell**) for -march= switch
 /*******************************************************************************
 ^
/home/hjku/workspace/taichi/src/util/zip.cpp:1:0: error: bad value (**haswell**) for -march= switch
 #include <taichi/taichi>
 ^
/home/hjku/workspace/taichi/src/sampler/sampler.cpp:1:0: error: bad value (**haswell**) for -march= switch
 /*******************************************************************************
 ^
/home/hjku/workspace/taichi/src/sampler/sobol.cpp:1:0: error: bad value (**haswell**) for -march= switch
 /*******************************************************************************
 ^
CMakeFiles/taichi_core.dir/build.make:182: recipe for target 'CMakeFiles/taichi_core.dir/src/volume_material/volume_material.cpp.o' failed
make[2]: *** [CMakeFiles/taichi_core.dir/src/volume_material/volume_material.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/taichi_core.dir/build.make:158: recipe for target 'CMakeFiles/taichi_core.dir/src/levelset/sdf.cpp.o' failed
make[2]: *** [CMakeFiles/taichi_core.dir/src/levelset/sdf.cpp.o] Error 1
CMakeFiles/taichi_core.dir/build.make:62: recipe for target 'CMakeFiles/taichi_core.dir/src/util/zip.cpp.o' failed
make[2]: *** [CMakeFiles/taichi_core.dir/src/util/zip.cpp.o] Error 1
CMakeFiles/taichi_core.dir/build.make:134: recipe for target 'CMakeFiles/taichi_core.dir/src/benchmark/mpm3_details.cpp.o' failed
make[2]: *** [CMakeFiles/taichi_core.dir/src/benchmark/mpm3_details.cpp.o] Error 1
CMakeFiles/taichi_core.dir/build.make:110: recipe for target 'CMakeFiles/taichi_core.dir/src/benchmark/spgrid.cpp.o' failed
make[2]: *** [CMakeFiles/taichi_core.dir/src/benchmark/spgrid.cpp.o] Error 1
CMakeFiles/taichi_core.dir/build.make:230: recipe for target 'CMakeFiles/taichi_core.dir/src/sampler/sampler.cpp.o' failed
make[2]: *** [CMakeFiles/taichi_core.dir/src/sampler/sampler.cpp.o] Error 1
CMakeFiles/taichi_core.dir/build.make:86: recipe for target 'CMakeFiles/taichi_core.dir/src/benchmark/simd.cpp.o' failed
make[2]: *** [CMakeFiles/taichi_core.dir/src/benchmark/simd.cpp.o] Error 1
CMakeFiles/taichi_core.dir/build.make:206: recipe for target 'CMakeFiles/taichi_core.dir/src/sampler/sobol.cpp.o' failed
make[2]: *** [CMakeFiles/taichi_core.dir/src/sampler/sobol.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/taichi_core.dir/all' failed
make[1]: *** [CMakeFiles/taichi_core.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
  Error: Build failed.
  Error: installation failed.

**Comment by yuanming-hu** [comment]
Oh, I see. That's an Sandy Bridge CPU that doesn't support AVX2. Let me figure out a way for that.

**Comment by yuanming-hu** [comment]
Could you do the following?
```
cd build
cmake .. -DTC_DISABLE_SIMD=True
make -j8
```

**Comment by bona00ku** [comment]
WOW! It finally works!!
Thank you sooo much!

**Comment by yuanming-hu** [comment]
Thanks. Making a piece of software running correctly on every machine is a tough job :-)

**Comment by forfor112** [comment]
Hi Yuanming,
I’ve the same issue with the VM above, which seems to disappear with changing TaichiCXXFlags.
By adjusting the cmake option, however, I got the following error [Illegal instruction (core dumped)] using Intel(R) Xeon(R) CPU E5-1620 v2 @ 3.70GHz
Thank you.
