### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by yuanming-hu** [yuanming-hu/taichi#15]
I plan to first have the documentation on the Python part, so that people can use it. The doc for C++ part will be put lower priority.

**Comment by IteratorAdvance** [comment]
BTW, if you guys have suggestions on how the documentation should be written (Doxygen/LaTeX/Markdown?), you are welcome to discuss here.

**Comment by yczhang89** [comment]
Sphinx? (http://www.sphinx-doc.org/en/1.5.1/) This is what readthedocs.io uses.

**Comment by yuanming-hu** [comment]
Thanks, @yczhang89. I'm starting to deal with documentation, possibly on http://readthedocs.io.

**Comment by yuanming-hu** [comment]
...after the APIs become more stable, of course.

**Comment by yuanming-hu** [comment]
This is becoming urgent as I myself start forgetting how to use `taichi`! I'll use Doxygen for this purpose. @jgfuchs

**Comment by yuanming-hu** [comment]
I started documenting stuff using Sphinx. This issue will be closed since it was open for discussing how documentation should be done, which is a too general topic. Detailed discussions should go to #131.
Thanks to @yczhang89 for proposing `Sphinx`, and I do find it suitable for this project.
