### ISSUE TITLE
Map with VectorI

### ISSUE THREAD

**Issue by squarefk** [yuanming-hu/taichi#150]
The output of the following code is confusing.

```
map<VectorI, bool> mp;
VectorI key1; key1[0]=32; key2[1]=79;
VectorI key2; key2[0]=34; key2[1]=79;
mp[key1] = true;
TC_WARN("{}", mp.find(key2)==mp.end());

```

The output is `0`

So the map doesn't work well with VectorI?

**Comment by yuanming-hu** [comment]
No, it will not work on VectorI. std::map operates on a total-order set while VectorI is only partially ordered. You need to specify an additional total order comparator for std::map with VectorI.
