### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by yuanming-hu** [yuanming-hu/taichi#16]

**Comment by beaugunderson** [comment]
would this work consist of creating a `Dockerfile` for testing purposes? (I can imagine it would be good for testing on Travis CI as well...)

**Comment by IteratorAdvance** [comment]
I think `Dockerfile` here will be just for configuration? Though it may be possible and necesary to do some testing after installation in `Docker`.

**Comment by yuanming-hu** [comment]
It seems that Taichi is designed to be light-weight therefore Docker may be too heavy for it...
