### ISSUE TITLE
Browser viewer

### ISSUE THREAD

**Issue by yuanming-hu** [yuanming-hu/taichi#18]
It would be good to have an additional browser viewer for rendering/simulation process visualization. Python itself has good HTTP server support and it will help in case people use Taichi for some task via ssh and do not want to enable X11 forwarding.

**Comment by chenxiaoqino** [comment]
I was thinking about this.

**Comment by IteratorAdvance** [comment]
I discussed with Yucheng(@yczhang89) about the possibility of using a fully web-based GUI, probably using [lovecat](https://github.com/CoffeeKitty/lovecat). Here I briefly summarize the discussion.

Pros:
 - No dependency on image viewer or other GUIs (Tkinter, OpenCV, Kivy, e.t.c.), we only need the HTTP server from `python` and a browser.
 - Allows remote control of rendering/simulation. 
 - For docker, access to GPU on Mac OS X and Windows is not possible so far, so Kivy will completely not work. Using a web-based GUI needs only opening an HTTP port.
 - Browsers automatically provide usual image display (png, jpg), and even videos.
 - Most output of Taichi is bounded by computation, so latency / IO bound on previewing is not an issue.
 - Even if we need to build a real-time preview, transmitting rendered images, say 1000px * 1000px at 20 FPS, requires only 60MB/s, which is acceptable for local server/client.
 - [lovecat](https://github.com/CoffeeKitty/lovecat) potentially provides nice interface for parameter tuning, and can reduce the amount of work on UI design.

Cons:
 - Not found yet. You are welcome to add some.

**Comment by yczhang89** [comment]
To link my previous rational: #11 (comment). IMO an important pro missing here is that, lovecat can do more things than a hard-coded UI. With lovecat, we could tune so many scene parameters (among others), which are unknown to taichi beforehand.

**Comment by yczhang89** [comment]
Two alternative approaches to handle scene parameters are:
1. Disallow ad hoc scene generation in Python, and requires all 3D scenes to be constructed from a set of predefined 'graph node'. Each predefined node gets a GUI. This is too restrictive IMO.
2. Provide an API `gui.request_parameter('parameter_name')`. This is essentially lovecat, and we could leverage lovecat to do this.

**Comment by yuanming-hu** [comment]
I'm building a `Flask` based one. Please refer to #66.
