### ISSUE TITLE
Is it expected that A*B matrix multiplication in Taichi is B.dot(A) in numpy?

### ISSUE THREAD

**Issue by r03ert0** [yuanming-hu/taichi#183]
I'm going over the 88 lines code, and found that A*B in taichi is B.dot(A) in numpy (or in general). The Mat*Vec multiplication is also rather unexpected (transposed(Mat)*Vec). Finally, the result of singular value decompositions USV=SVD(Mat) seems to be VSU=SVD(Mat). Is there a general pattern for all this?

Thanks !

roberto

**Comment by yuanming-hu** [comment]
In taichi A[x][y] means the col x and row y. This is for performance considerations. Use A(x, y) for row x and col y.

**Comment by r03ert0** [comment]
thanks!
