### ISSUE TITLE
hello ,I want to figure out what' the one of example is the first of picture that show the water affect wheel

### ISSUE THREAD

**Issue by ThunderLT** [yuanming-hu/taichi#194]

**Comment by yuanming-hu** [comment]
Hi please find it here: https://github.com/yuanming-hu/taichi_mpm/blob/master/scripts/mls-cpic/water_wheel.py

You may need to tweak the parameters a bit to get the exact dynamics.

**Comment by ThunderLT** [comment]
> Hi please find it here: https://github.com/yuanming-hu/taichi_mpm/blob/master/scripts/mls-cpic/water_wheel.py
> 
> You may need to tweak the parameters a bit to get the exact dynamics.

谢谢大佬
