### ISSUE TITLE
test.py failed on MacOSX

### ISSUE THREAD

**Issue by iamyoukou** [yuanming-hu/taichi#21]
The 13th line of `test.py` 
    `show_image('img', img)`
doesn't work. It never response.
<img width="467" alt="taichi_test_1" src="https://cloud.githubusercontent.com/assets/7427716/21752227/e6dcf9da-d617-11e6-81a9-04e6c3650ec1.png">

When I comment out `show_image('img', img)`, the program ends correctly.
<img width="434" alt="taichi_test_2" src="https://cloud.githubusercontent.com/assets/7427716/21752228/e6df7304-d617-11e6-96db-b0a6ff8dacd8.png">

Maybe there is something wrong with show_image?

**Comment by iamyoukou** [comment]
When I use
```
from PIL import Image
...
img = Image.open(tc.get_asset_path('textures/vegas.jpg'))
img.show()
...
```
instead of the original
```
...
img = tc.util.imread(tc.get_asset_path('textures/vegas.jpg'))
show_image('img', img)
...
```
the program executed correctly.
<img width="138" alt="testoutput" src="https://cloud.githubusercontent.com/assets/7427716/21758583/9b5b5844-d680-11e6-8004-b9467d3bce34.png">

So I think there's something strange with `show_image()`

**Comment by IteratorAdvance** [comment]
Thanks for the feedback. Do you mind providing more clues by showing on which python script it fails?

**Comment by iamyoukou** [comment]
Sorry, maybe it is `get_asset_path()`'s problem.  
I tried `print tc.get_asset_path('textures/vegas.jpg')`, and it returns  
<img width="568" alt="problem" src="https://cloud.githubusercontent.com/assets/7427716/21759365/19b2599e-d687-11e6-8466-b7c0ddc69506.png">
And my `~/.bashrc` is
<img width="557" alt="path" src="https://cloud.githubusercontent.com/assets/7427716/21759379/348e7374-d687-11e6-90d0-a981275c8e4a.png">

The `get_asset_path(path)` function in `python/taichi/misc/settings.py` probably works differently on my MacOSX.

**Comment by IteratorAdvance** [comment]
I think extra slashes will be ignored so it may not be the cause. You can try press Ctrl-C when it's blocked and paste the python call stack & error info here. Thanks.

**Comment by iamyoukou** [comment]
You're right, not the extra slashes problem.  
And sorry, I don't know how to get python call stack & error info.  
I googled and tried this
I tried
```
try:
    img = tc.util.imread(tc.get_asset_path('textures/vegas.jpg'))
except Exception:
    print(traceback.print_stack())
```
But it outputs nothing after I Ctrl-C (BTW, on my MacOSX, Ctrl+C doesn't work, but Ctrl+\ works)

**Comment by IteratorAdvance** [comment]
Thanks for trying this. I guess it should be blocked in `show_image` where `taichi.gui.tk.viewer.__init__` was called. You can try to add some `print`s and see where the script was blocked.

Sorry to get you so involved in this issue. Hopefull we can find something interesting and learn something.

**Comment by iamyoukou** [comment]
I can always learn new things when solving a problem and I'm happy with it, so don't worry about the "so-involved" thing.  
And I found that the script is blocked at `tk_root = tk.Tk()`
in `taichi.gui.tk.viewer.get_tk_root`

**Comment by IteratorAdvance** [comment]
Thanks. Then you can just open an interative python console, type
```
import Tkinter as tk
tk_root = tk.Tk()
```
and see if it blocks.

**Comment by iamyoukou** [comment]
Yeah, it blocks

**Comment by IteratorAdvance** [comment]
Interesting... It seems that a problem of Tk then.

**Comment by IteratorAdvance** [comment]
On my Windows machine invoking `Tk.tk()` opens a window and returns. Did you see any window?

**Comment by iamyoukou** [comment]
No, nothing.  
BTW, what will happen if you try the following code?
```
from Tkinter import *

root = Tk()
button = Button(root, text = 'Python/Tkinter')
button.pack()
root.mainloop()
```

**Comment by IteratorAdvance** [comment]
I get a small window with a botton, as described by the code.

**Comment by iamyoukou** [comment]
And I get blocked... X_X

**Comment by IteratorAdvance** [comment]
I googled about this problem yet found no similar result. What's the version of your TkinterYou can get it via
```
import Tkinter as tk
print tk.__version__
```
You may also want to check the version of Tk (Tkinter is it's python binding) installed by MacPort. Maybe it's too old and do not suit well with your OS X version.

**Comment by iamyoukou** [comment]
I got `$Revision: 81008 $`  
And I just found there is a `py27-tkinter` on MacPorts, and I installed it.
But `python2.7` keeps using the old version, not `py27-tkinter`

**Comment by IteratorAdvance** [comment]
My revision is also `$Revision: 81008 $`. How about 
```
print tk.TkVersion
```
? Mine is `8,5`.

**Comment by iamyoukou** [comment]
Mine is `8.6`

**Comment by IteratorAdvance** [comment]
It sounds that nothing is wrong... The last thing I can help is to write a Kivy image viewer as an alternative to Tk, but it takes some time. If you can install OpenCV (cv2 in python), you can simply replace `show_image('title', img)` with `cv2.imshow('title', img); cv2.waitKey(1)` and you no longer need Tk to play with Taichi. Thanks.

**Comment by iamyoukou** [comment]
```
cv2.imshow('title', img)
cv2.waitKey(1)
```
works! I replaced the `show_image('Vis', img)` in mgpcg_smoke_3d.py, and I got correct output:
![image](https://cloud.githubusercontent.com/assets/7427716/21762590/e14ee976-d69c-11e6-8b30-30461428d867.png)

Thank you very much!

As for the `Tkinter` problem, I also posted it on [stackoverflow].(http://stackoverflow.com/questions/41544748/macosx-tkinter-no-response-when-tk?noredirect=1#comment70294395_41544748)
Can you put this issue open until there is a solution (probably)?

**Comment by IteratorAdvance** [comment]
Cool. OpenCV was the original solution I took. I also do some computer vision research, but most people may not have it and installing OpenCV can be troublesome on Windows. So I added Kivy and @beaugunderson kindly added Tk.

@beaugunderson do you know how to deal with this Tk issue? Thanks.

**Comment by iamyoukou** [comment]
Found something weird.  
I have two `Python2.7` on my MacOSX.  
One is `python`. It is pre-installed by MacOSX, and its version is `2.7.10`.  
The other one is `python2.7`. I installed it using MacPorts, and its version is `2.7.13`.  
For the code bellow
```
from Tkinter import *

root = Tk()
button = Button(root, text = 'Python/Tkinter')
button.pack()
root.mainloop()
```
When using `python` to execute it, I got correct output
<img width="468" alt="tkcorrect" src="https://cloud.githubusercontent.com/assets/7427716/21763704/90a79b0c-d6a2-11e6-9a9b-1f728a4421a0.png">

When using `python2.7`, I got blocked
<img width="361" alt="tkstuck" src="https://cloud.githubusercontent.com/assets/7427716/21763718/a542bf74-d6a2-11e6-9065-acaac38be573.png">

**Comment by IteratorAdvance** [comment]
I also have two Pythons, pre-installed 2.7.10 and brew-installed 2.7.8. Both run Tk well, though. X_X

**Comment by beaugunderson** [comment]
Hmm, I have not seen this Tk issue either!

It sounds like you're saying the MacPorts python executable is using the system installation of Tk though... That sounds like it might cause the issue? But I'm not sure how to force python to use the MacPorts version...

**Comment by iamyoukou** [comment]
@beaugunderson I think `python2.7`(MacPorts) is using MacPorts-version Tk. I try the code bellow with both `python`(system) and `python2.7`(MacPorts)
```
import Tkinter as tk
print tk.TkVersion
```
and the output is `8.5`(system) and `8.6`(MacPorts).  
So I think perhaps MacPorts python doesn't work well with MacPorts Tk.

**Comment by Archer-zty** [comment]
@yuanming-hu 
Hi, I am new to python. There is a fooooolish problem when I running `python test.py` that makes me fell helpless...
`test $python test.py
Traceback (most recent call last):
  File "test.py", line 2, in <module>
    import taichi as tc
  File "/usr/local/lib/python2.7/site-packages/taichi/__init__.py", line 1, in <module>
    from taichi.core import tc_core as core
ImportError: No module named core`

I have installed taichi through pip
`test $pip install taichi
Requirement already satisfied: taichi in /usr/local/lib/python2.7/site-packages`
and the compilation for source code is successful
`[  1%] Linking CXX shared library ../build/libtaichi_core.dylib
[100%] Built target taichi_core`
Thank you.

**Comment by yuanming-hu** [comment]
Did you use `pip install taichi` to get the python scripts? This may not work now. Please first 'pip uninstall taichi' and then follow https://github.com/yuanming-hu/taichi/wiki/Installation 

After you add 'export PYTHONPATH=$TAICHI_ROOT_DIR/taichi/python/:$PYTHONPATH', `python` will find the python part of `taichi` automatically - no need for 'pip install taichi'.

**Comment by Archer-zty** [comment]
@yuanming-hu 
I see. It works. 
Thank you.

**Comment by yuanming-hu** [comment]
Visualization will be based on browser thereby `tk` will no longer be needed.
