### ISSUE TITLE
Installation fails on MacOS

### ISSUE THREAD

**Issue by andri221** [yuanming-hu/taichi#210]
Installation is giving me a hard time. Building seems ok, but the last step fails (see attached output). Any idea? This sounds like an interesting project and I really wish I could install it.
Thanks

My configuration is the following: 

**************************************************
* CPU feature detection done.
* Using Instruction Set Externsion: [AVX2]
**************************************************
Clang compiler detected. Using std=c++17.
Using float32 (single) precision as real
Using -D_GLIBCXX_USE_CXX11_ABI=0
Using /anaconda2/envs/py36/bin/python3.6 as python executable.
Python 3.6.7
    version: 3.6
    include: /anaconda2/envs/py36/include/python3.6m
    library: /anaconda2/envs/py36/lib/libpython3.6m.dylib
    numpy include: /anaconda2/envs/py36/lib/python3.6/site-packages/numpy/core/include
    pybind11 include: /anaconda2/envs/py36/include;/anaconda2/envs/py36/include
Runtimes exist.
PYTHON_LIBRARIES/anaconda2/envs/py36/lib/libpython3.6m.dylib
---------------------------------------------------------------
Ignoring project examples. (No CMakeLists.txt.)
---------------------------------------------------------------
C++ Flags:  -DTC_ISE_AVX2 -std=c++17 -march=native         -DGL_DO_NOT_WARN_IF_MULTI_GL_VERSION_HEADERS_INCLUDED -Wall -DTC_PASS_EXCEPTION_TO_PYTHON -DTC_INCLUDED -D_GLIBCXX_USE_CXX11_ABI=0 -g

And this here is the error message I get at the end.

[T 09/23/19 15:19:52.594] [logging.cpp:Logger@67] Taichi core started. Thread ID = 25641
Fatal Python error: PyThreadState_Get: no current thread

[E 09/23/19 15:19:52.595] Received signal 6 (Abort trap: 6)

                            * Taichi Core - Stack Traceback *                             
==========================================================================================
|                       Module |  Offset | Function                                      |
|----------------------------------------------------------------------------------------|
*               taichi_core.so |     297 | taichi::signal_handler(int)                   |
*     libsystem_platform.dylib |      26 | (null)                                        |
*                          ??? |      60 | (null)                                        |
*            libsystem_c.dylib |     127 | (null)                                        |
*          libpython3.6m.dylib |     741 | (null)                                        |
*          libpython3.6m.dylib |     699 | (null)                                        |
*               taichi_core.so |     228 | (null)                                        |
*                    python3.6 |     473 | (null)                                        |
*                    python3.6 |     188 | (null)                                        |
*                    python3.6 |      66 | (null)                                        |
*                    python3.6 |   47554 | (null)                                        |
*                    python3.6 |     425 | (null)                                        |
*                    python3.6 |     362 | (null)                                        |
*                    python3.6 |     236 | (null)                                        |
*                    python3.6 |   46802 | (null)                                        |
*                    python3.6 |     188 | (null)                                        |
*                    python3.6 |     236 | (null)                                        |
*                    python3.6 |   46802 | (null)                                        |
*                    python3.6 |     188 | (null)                                        |
*                    python3.6 |     236 | (null)                                        |
*                    python3.6 |   46802 | (null)                                        |
*                    python3.6 |     188 | (null)                                        |
*                    python3.6 |     236 | (null)                                        |
*                    python3.6 |   46802 | (null)                                        |
*                    python3.6 |     188 | (null)                                        |
*                    python3.6 |     236 | (null)                                        |
*                    python3.6 |   46802 | (null)                                        |
*                    python3.6 |     175 | (null)                                        |
*                    python3.6 |     320 | (null)                                        |
*                    python3.6 |     490 | (null)                                        |
*                    python3.6 |    1092 | (null)                                        |
*                    python3.6 |   38784 | (null)                                        |
*                    python3.6 |     425 | (null)                                        |
*                    python3.6 |     345 | (null)                                        |
*                    python3.6 |      66 | (null)                                        |
*                    python3.6 |   47554 | (null)                                        |
*                    python3.6 |     425 | (null)                                        |
*                    python3.6 |     362 | (null)                                        |
*                    python3.6 |     236 | (null)                                        |
*                    python3.6 |   46802 | (null)                                        |
*                    python3.6 |     188 | (null)                                        |
*                    python3.6 |     236 | (null)                                        |
*                    python3.6 |   46802 | (null)                                        |
*                    python3.6 |     188 | (null)                                        |
*                    python3.6 |     236 | (null)                                        |
*                    python3.6 |   46802 | (null)                                        |
*                    python3.6 |     188 | (null)                                        |
*                    python3.6 |     236 | (null)                                        |
*                    python3.6 |   46802 | (null)                                        |
*                    python3.6 |     175 | (null)                                        |
*                    python3.6 |     320 | (null)                                        |
*                    python3.6 |     490 | (null)                                        |
*                    python3.6 |    1092 | (null)                                        |
*                    python3.6 |   38784 | (null)                                        |
*                    python3.6 |     425 | (null)                                        |
*                    python3.6 |     345 | (null)                                        |
*                    python3.6 |      66 | (null)                                        |
*                    python3.6 |   47554 | (null)                                        |
*                    python3.6 |     425 | (null)                                        |
*                    python3.6 |     362 | (null)                                        |
*                    python3.6 |     236 | (null)                                        |
*                    python3.6 |   46802 | (null)                                        |
*                    python3.6 |     188 | (null)                                        |
*                    python3.6 |     236 | (null)                                        |
*                    python3.6 |   46802 | (null)                                        |
*                    python3.6 |     188 | (null)                                        |
*                    python3.6 |     236 | (null)                                        |
*                    python3.6 |   46802 | (null)                                        |
*                    python3.6 |     188 | (null)                                        |
*                    python3.6 |     236 | (null)                                        |
*                    python3.6 |   46802 | (null)                                        |
*                    python3.6 |     175 | (null)                                        |
*                    python3.6 |     320 | (null)                                        |
*                    python3.6 |     490 | (null)                                        |
*                    python3.6 |    1092 | (null)                                        |
*                    python3.6 |   38784 | (null)                                        |
*                    python3.6 |     425 | (null)                                        |
*                    python3.6 |     345 | (null)                                        |
*                    python3.6 |      66 | (null)                                        |
*                    python3.6 |   47554 | (null)                                        |
*                    python3.6 |     425 | (null)                                        |
*                    python3.6 |     362 | (null)                                        |
*                    python3.6 |     236 | (null)                                        |
*                    python3.6 |   46802 | (null)                                        |
*                    python3.6 |     188 | (null)                                        |
*                    python3.6 |     236 | (null)                                        |
*                    python3.6 |   46802 | (null)                                        |
*                    python3.6 |     188 | (null)                                        |
*                    python3.6 |     236 | (null)                                        |
*                    python3.6 |   46802 | (null)                                        |
*                    python3.6 |     188 | (null)                                        |
*                    python3.6 |     236 | (null)                                        |
*                    python3.6 |   46802 | (null)                                        |
*                    python3.6 |     175 | (null)                                        |
*                    python3.6 |     320 | (null)                                        |
*                    python3.6 |     490 | (null)                                        |
*                    python3.6 |    1092 | (null)                                        |
*                    python3.6 |   38784 | (null)                                        |
*                    python3.6 |     425 | (null)                                        |
*                    python3.6 |     345 | (null)                                        |
*                    python3.6 |      66 | (null)                                        |
*                    python3.6 |   47554 | (null)                                        |
*                    python3.6 |     425 | (null)                                        |
*                    python3.6 |     362 | (null)                                        |
*                    python3.6 |     236 | (null)                                        |
*                    python3.6 |   46802 | (null)                                        |
*                    python3.6 |     188 | (null)                                        |
*                    python3.6 |     236 | (null)                                        |
*                    python3.6 |   46802 | (null)                                        |
*                    python3.6 |     188 | (null)                                        |
*                    python3.6 |     236 | (null)                                        |
*                    python3.6 |   46802 | (null)                                        |
*                    python3.6 |     188 | (null)                                        |
*                    python3.6 |     236 | (null)                                        |
*                    python3.6 |   46802 | (null)                                        |
*                    python3.6 |     175 | (null)                                        |
*                    python3.6 |     320 | (null)                                        |
*                    python3.6 |     490 | (null)                                        |
*                    python3.6 |    1092 | (null)                                        |
*                    python3.6 |   38784 | (null)                                        |
*                    python3.6 |     425 | (null)                                        |
*                    python3.6 |     345 | (null)                                        |
*                    python3.6 |      66 | (null)                                        |
*                    python3.6 |   47554 | (null)                                        |
*                    python3.6 |     425 | (null)                                        |
*                    python3.6 |     362 | (null)                                        |
*                    python3.6 |     236 | (null)                                        |
==========================================================================================

  Error: installation failed.

**Comment by yuanming-hu** [comment]
Hi andri221,

We are migrating to the new Taichi programming language, which has better compatibility. The old Taichi library is no longer maintained. Sorry!
