### ISSUE TITLE
implement clear_data_and_deactivate for CPU

### ISSUE THREAD

**Issue by KLozes** [yuanming-hu/taichi#227]
clear_data() and clear_data_and_deactivate() is currently only implemented with cuda backend. Will it be implemented for x86_64 in the future?

**Comment by yuanming-hu** [comment]
Hi KLozes,

I'm working on an LLVM backend to replace the current C++/CUDA backend. The LLVM backend will be online sometime next week with these functionalities.

Thanks,
Yuanming

**Comment by KLozes** [comment]
Hi Yuanming,

Sounds good, thanks for the reply.

Also, I was about to submit another issue. Its seems that the numpy
integration is broken with the new python wheels build. You should be able
to reproduce the error by running the numpy example.

Thanks,
Kenny

**Comment by yuanming-hu** [comment]
Thanks! I'll take a look.
