### ISSUE TITLE
Error importing taichi

### ISSUE THREAD

**Issue by Veloc1tyE** [yuanming-hu/taichi#253]
Here is what happens when I try to import taichi

In [1]: import taichi as ti                                                                                                                                                                   
/home/veloc1ty/taichi/build
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-1-a49150b41477> in <module>
----> 1 import taichi as ti

~/taichi/python/taichi/__init__.py in <module>
----> 1 from taichi.main import main
      2 from taichi.core import tc_core
      3 from taichi.core import start_memory_monitoring
      4 from taichi.misc.util import vec, veci, set_gdb_trigger, set_logging_level, info, warning, error, debug, trace
      5 from taichi.tools import *

~/taichi/python/taichi/main.py in <module>
      4 import time
      5 import random
----> 6 from taichi.tools.video import make_video, interpolate_frames
      7 
      8 def test_python():

~/taichi/python/taichi/tools/video.py in <module>
      1 from taichi.misc.util import ndarray_to_array2d, array2d_to_ndarray
      2 from taichi.misc.settings import get_os_name, get_directory
----> 3 import taichi.core as core
      4 import os
      5 

~/taichi/python/taichi/core/__init__.py in <module>
----> 1 from .util import tc_core, build, format, load_module, start_memory_monitoring
      2 from .unit import unit
      3 
      4 tc_core.build = build
      5 tc_core.format = format

~/taichi/python/taichi/core/util.py in <module>
    155       os.environ['LD_LIBRARY_PATH'] = '/usr/lib64/'
    156     print(bin_dir)
--> 157     assert os.path.exists(os.path.join(bin_dir, 'libtaichi_core.so'))
    158     tmp_cwd = os.getcwd()
    159     os.chdir(bin_dir)

It says the file is setting the bin directory to /home/veloc1ty/taichi/build, which does not exit. I'm not sure why this doesn't work, everything is configured correctly

**Comment by yuanming-hu** [comment]
Thanks for the feedback. You installed taichi-nightly with pip, right? Also please let me know your OS.

**Comment by Veloc1tyE** [comment]
Hi yuanming, yes I installed it with pip, my OS is centOS 8

**Comment by Veloc1tyE** [comment]
Also I had python installed through Anaconda so I changed the Python path to /home/veloc1ty/anaconda3/bin/python, but encountered the same issue

**Comment by yuanming-hu** [comment]
Thanks for the reply.
what's your
```
echo $TAICHI_REPO_DIR
```
? Is it an empty string?

**Comment by Veloc1tyE** [comment]
This returns /home/veloc1ty/taichi

**Comment by yuanming-hu** [comment]
I see. What happens if you follow the second bullet of the Notes (https://github.com/yuanming-hu/taichi/blob/master/README.md#updates) "Make sure you clear your legacy Taichi installation"

**Comment by Veloc1tyE** [comment]
In [1]: import taichi as ti                                                     
[Release mode]
[T 11/04/19 15:09:48.549] [logging.cpp:Logger@67] Taichi core started. Thread ID = 31785
Using CUDA Device [0]: GeForce RTX 2080
Device Compute Capability: 7.5
[Taichi version 0.0.79, cuda 10.1, commit 1b1bc591]

This is what happens

**Comment by Veloc1tyE** [comment]
Thank you so much! Sorry for overlooking that ....

**Comment by yuanming-hu** [comment]
Cool :-)
