### ISSUE TITLE
Is there a way to manually call place?

### ISSUE THREAD

**Issue by aespielberg** [yuanming-hu/taichi#257]
I would like to create my scene of particles dynamically, figure out how many there are in the scene, and then set up all the tensors.  Is there a way to do this or does it have to be known statically?

**Comment by yuanming-hu** [comment]
The example to check out is: https://github.com/yuanming-hu/taichi/blob/master/examples/difftaichi/diffmpm3d.py#L16

Tensors are materialized on first data access/kernel launch, so you can always change the global `n_particles` var before that, and after you know how many particles you have.

**Comment by aespielberg** [comment]
Thanks for the clarification.
