### ISSUE TITLE
MacOSX: unsafe use of relative rpath libboost_system.dylib

### ISSUE THREAD

**Issue by iamyoukou** [yuanming-hu/taichi#26]
After I built `libtaichi_core.dylib` and run the test code, I have this error
```
>>> import taichi as tc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/YJ-work/Desktop/taichi_root/taichi/python/taichi/__init__.py", line 1, in <module>
    from taichi.core import tc_core as core
  File "/Users/YJ-work/Desktop/taichi_root/taichi/python/taichi/core/__init__.py", line 2, in <module>
    from load_core import tc_core
  File "/Users/YJ-work/Desktop/taichi_root/taichi/python/taichi/core/load_core.py", line 18, in <module>
    import taichi_core as tc_core
ImportError: dlopen(./taichi_core.so, 2): Library not loaded: libboost_system.dylib
  Referenced from: /Users/YJ-work/Desktop/taichi_root/taichi/build/taichi_core.so
  Reason: unsafe use of relative rpath libboost_system.dylib in ./taichi_core.so with restricted binary
```
I googled and found the problem is in `libtaichi_core.dylib`:
```
aibm8:build YJ-work$ otool -L libtaichi_core.dylib 
libtaichi_core.dylib:
	/Users/YJ-work/Desktop/taichi_root/taichi/build/libtaichi_core.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1226.10.1)
	/opt/local/lib/libembree.2.dylib (compatibility version 2.0.0, current version 2.13.0)
	/System/Library/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.10)
	/opt/local/lib/libboost_system-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	/opt/local/lib/libboost_python-mt.dylib (compatibility version 0.0.0, current version 0.0.0)
	libboost_system.dylib (compatibility version 0.0.0, current version 0.0.0)
	libboost_python.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.1.0)
```
And I changed the path `libboost_system.dylib`, `libboost_python.dylib` to:
```
/opt/local/lib/libboost_system.dylib (compatibility version 0.0.0, current version 0.0.0)
/opt/local/lib/libboost_python.dylib (compatibility version 0.0.0, current version 0.0.0)
```
then the error is gone.
The problem is: every time I rebuild `libtaichi_core.dylib`, I have to repeat the above things again.  
Is there any way to solve this problem?

`/opt/local/lib` is where I put `libboost_system.dylib` and `libboost_python.dylib`.

**Comment by IteratorAdvance** [comment]
Hi Jiang,

Are there `libboost_system.dylib` and `libboost_python.dylib` in `$TAICHI_ROOT_DIR/taichi/build/`?   If so, when `libtaichi_core.dylib` is being built, I guess these 2 libs will be linked with higher priority than those in `/opt/local/lib`, resulting in relative dll path.

Please check the folder, remove the libs if they exist, and then rebuild. If the linker fails to find the two boost libs, try copying the 2 libs to `/usr/local/lib`. 

Thanks,
Yuanming

**Comment by iamyoukou** [comment]
No `libboost_system.dylib` and `libboost_python.dylib` are in `$TAICHI_ROOT_DIR/taichi/build/`, and I already copied these two boost libs into `/usr/local/lib`.  
It seems that if I use `python` that pre-installed by `MacOSX`, this `unsafe use` issue will happen.  
But if I use `python2.7` from `MacPorts`, nothing wrong will happen.  
I think I'll just use `python2.7(MacPorts)` to avoid this issue.
Thank you very much : )

**Comment by yuanming-hu** [comment]
Dependency on `boost` is removed so this should no longer be an issue. Please reinstall `taichi` and make sure to install `pybind11`, as described in [Installation](https://github.com/yuanming-hu/taichi/wiki/Installation).
