### ISSUE TITLE
How is total_energy used in the lagrangian forces example?

### ISSUE THREAD

**Issue by aespielberg** [yuanming-hu/taichi#265]
https://github.com/yuanming-hu/taichi/blob/master/examples/mpm_lagrangian_forces.py

It seems that the total_energy is key to everything, but as far as I can tell, it's never explicitly used.  There seems to be some magic about using its grad to apply forces.  Is there an explanation of how this works, programmatically (not the physics/math, that all makes sense).

**Comment by yuanming-hu** [comment]
https://github.com/yuanming-hu/taichi/blob/master/examples/mpm_lagrangian_forces.py#L172

Added a few lines of comments here - let me know if that answers your question!

**Comment by aespielberg** [comment]
Okay, I think I understand:

1. We compute the energy.  We do this in a with Tape block, so
backpropagation also happens.  This populates the x.grad for the timestep.
2. Then, we perform our remaining p2g, g2p, and grid op steps.

This is interesting.  But, this will lead to a problem if one also wants to
optimize this system, right?  The gradients of this simulation won't be
correct.  x.grad was calculated once already for the time step, and then x
is overwritten later in the g2p step.  If one wants to backprop through the
entire simulation, then, x.grad gets written twice (once in the energy
step, and once in the g2p backprop), and they will clobber each other.

Is this correct?  Or can one generally also backpropagate through this?

I ask especially because thi sseems an extremely convenient way of defining
and optimizing other physical phenomena (elastic cables, springs, etc.),
and it would be nice if such a system worked without having to derive
forces manually from potential functions

**Comment by yuanming-hu** [comment]
Right, if you use this together with optimization, (ti.Tape inside ti.Tape) then I have no idea what you will get with the current code...

**Comment by aespielberg** [comment]
I see.  Okay, this makes using this (admittedly, very cool) formulation a
little trickier.  I'll put the kibosh on this for now and come back to it
later if there's some simple way to implement this in the general case.
