### ISSUE TITLE
Is there a way to compute the svd in the code currently?

### ISSUE THREAD

**Issue by aespielberg** [yuanming-hu/taichi#266]
Also, sorry for so many questions...

**Comment by yuanming-hu** [comment]
Not yet - Please use NeoHookean for now. I will add support for this later.

**Comment by aespielberg** [comment]
Okay, thanks.  Main reason is I am trying to implement the explicit
time-stepping version of this paper:
https://www.seas.upenn.edu/~cffjiang/research/fang2019visco/fang2019visco.pdf
so I can more faithfully simulate viscoelastoplastic foams for the physical
world.

It looks easy to implement, but requires the Hencky strain tensor, which
requires SVD.

**Comment by yuanming-hu** [comment]
I see! It's not too hard (but probably needs a couple of hours) to add support for this (using Eftychios's implementation)..

**Comment by aespielberg** [comment]
I should ask - do you think this is on the roadmap at all?

**Comment by yuanming-hu** [comment]
Yes, I'll do it after I finish traveling, e.g. 3-4 days later. This can be a bit tricky since the SVD uses an iterative solver, and needs gradients.

**Comment by yuanming-hu** [comment]
This is implemented as `ti.svd(A, data_type)` (https://github.com/yuanming-hu/taichi/blob/master/tests/python/test_svd.py) and will be released tomorrow in v0.3.4.

**Comment by aespielberg** [comment]
Thank you so much!  Is this just for forward, or is this also for backward?

**Comment by yuanming-hu** [comment]
Just forward. Releasing with v0.3.4 in an hour.
