### ISSUE TITLE
Indexing into vectors in sums

### ISSUE THREAD

**Issue by aespielberg** [yuanming-hu/taichi#271]
The following code works, where v_avg is a vec():

ti.root.dense(ti.i, steps).place(v_avg)

```
@ti.kernel
def compute_v_avg(s: ti.i32):
  for i in range(globals.n_particles):
    contrib = 1.0 / globals.n_particles
    v_avg[s].atomic_add(contrib * v[s, i])
```

The following code does not work.  Here, obs is also a vec():

```
@ti.kernel
def compute_obs(s: ti.i32):
  for j in range(n_obs // 2):
    obs[s][j] = 0.0
    for i in range(globals.n_particles):
      contrib = 1.0 / globals.n_particles
      obs[s][j].atomic_add(contrib * v[s, i][j])
      
  for j in range(n_obs // 2):
    for i in range(globals.n_particles):
      contrib = 1.0 / globals.n_particles
      obs[s][n_obs // 2 + j].atomic_add(contrib * x[s, i][j])
```

This leads me to two questions:

1. What is the cause of this error?

2. Is there any equivalent of tf.stack, for the cases where I want to, say, make an observation vector that's a bunch of other vectors stacked on top of each other?

**Comment by yuanming-hu** [comment]
1. The indexing into the taichi matrices must be a compile-time constant. Indexing into taichi tensors can be run-time variables. `obs` is a tesnor of vector(matrix), so you access that as `obs[tensor_index][matrix index]`. The first index can be variable, yet the second must be a constant. 

I would try something like
```python
@ti.kernel
def reset_obs(s: ti.i32):
   for j in ti.static(range(n_obs // 2)): # unroll for loop to get a compile-time constant j
     # btw should n_obs // 2 be n_obs here? 
     obs[s][j] = 0.0

@ti.kernel
def compute_obs(s: ti.i32):
  for i in range(globals.n_particles):
    contrib = 1.0 / globals.n_particles
    for j in ti.static(range(n_obs // 2)): # unroll for loop to get a compile-time constant j
      obs[s][j].atomic_add(contrib * v[s, i][j])    
    for j in ti.static(range(n_obs // 2)): # unroll for loop to get a compile-time constant j
      obs[s][n_obs // 2 + j].atomic_add(contrib * x[s, i][j])
```

2. Currently, no. However, you can allocate a tensor and copy component vectors into that tensor using a kernel.

**Comment by yuanming-hu** [comment]
Btw, it seems more reasonable to me to use a 2D tensor of scalars instead of 1D tensor of 1D vectors here. Vector/Matrices are just for small linalg elements, such as 2x2 and 3x1 matrices (vectors).
