### ISSUE TITLE
Proper way to do substepping?

### ISSUE THREAD

**Issue by aespielberg** [yuanming-hu/taichi#272]
I'm trying to add substepping to the simulation.  To do this, I change the advance and the advance_grad:

```
@ti.complex_kernel
def advance(s: ti.i32):
  clear_grid()
  v_avg[s] = zero_vec_list()
  
  if ti.static(s % mult == 0):
    compute_v_avg(s)
    nn1(s)
    nn2(s)
  else:
    copy_act(s)
  
  
  p2g(s)
  grid_op()
  g2p(s)
```

```
@ti.complex_kernel_grad(advance)
def advance_grad(s: ti.i32):
  clear_grid()
  p2g(s)
  grid_op()
  
  
  g2p.grad(s)
  grid_op.grad()
  p2g.grad(s)
  #compute_actuation2.grad(s)
  if ti.static(s % mult == 0):
    nn2.grad(s)
    nn1.grad(s)
    compute_v_avg.grad(s)
  else:
    copy_act.grad(s)
```
where compute_v_avg, nn1, and nn2 are part of the controller.  copy_act, a different function, just copies the last computed controller input.

```
@ti.kernel
def copy_act(s: ti.i32):
  for j in range(actuations):
    actuation[s, j] = actuation[s - 1, j]
```

I don't  see _significant_ speedup by substepping (it is already running quite fast, and there is a small speedup), so I just wanted to make sure - is this the correct way to do this?

**Comment by yuanming-hu** [comment]
Hi Andy, please use the raw if statememt here. static if is for a branching that is compile time constant, like if-constexpr in C++17.  Apart from that your implementation looks good to me. I don't expect a significant speed up (something more than 2x) by doing substepping in taichi,  as controller evaluation is fast enough.

**Comment by aespielberg** [comment]
I am actually finding that this is slowing things down without the ti.static, both in compilation and runtime.  Any idea why this could be?

**Comment by yuanming-hu** [comment]
`ti.static` outside Taichi scope may always return `True`, and this might be the cause. Now Taichi does not allow using `ti.static` outside Taichi kernels.

**Comment by aespielberg** [comment]
Gotcha.  I will try this ASAP.

**Comment by aespielberg** [comment]
Compilation is still very slow, even without ti.static.  Is this expected?

**Comment by yuanming-hu** [comment]
Could you share with me a sample code to reproduce? Thanks!!

**Comment by aespielberg** [comment]
git id 738c1d26969229bb51026a05d973a9b5d65fe5ac in my other repo.  Run test_mpm_simulator.py,

**Comment by yuanming-hu** [comment]
Hi Andy,

It's probably not stuck at compilation. According to your code, it seems that you are allocating a huge array of 400k time steps and 12.4K particles. Your machine will be stuck because of running out of memory. It will run smoothly (although make no progress) if you use `MPMSim(time=0.004)`.

**Comment by aespielberg** [comment]
Hi Yuanming,

Sorry, you are right in that there was an obvious error there, in that I meant to set dt = 1e-2, mult=10.  However, there are three problems when you do this as compared to mult=1, dt=1e-3.  First, everything takes longer to compile.  Second, everything takes SIGNIFICANTLY longer to simulate, by which I mean about 5x slower.  Third, the optimization results make less sense.  I suspect there is still something wrong here.

I can try to reformulate this as just for loops, but I'd like to understand when this fails and why this fails and if there is some sort of bug under the hood.

**Comment by yuanming-hu** [comment]
"Second, everything takes SIGNIFICANTLY longer to simulate, by which I mean about 5x slower"

Around line 85 of mpm_simulator.py, I see 
```
    self.dt = dt / mult
    ...
    self.steps = int(time / self.dt * mult)
```
should this be 
```
    self.dt = dt / mult
    self.steps = int(time / self.dt)
```
?
It's natural to me that "dt = 1e-2, mult=10" takes 5x more time than "mult=1, dt=1e-3" since you are doing 10x more work and allocate 10x more memory. Compilation may also take slightly more time when your memory allocation is more aggressive.
