### ISSUE TITLE
llvm ptx back end very slow when using struct_for loop

### ISSUE THREAD

**Issue by KLozes** [yuanming-hu/taichi#296]
On my computer the double for loop kernel is 300x faster than the struct_for kernel when using cuda. The timings are comparable when using the x86_64. 

``` python
import taichi as ti
import time
#ti.cfg.arch = ti.x86_64
ti.cfg.arch = ti.cuda

a = ti.var(dt=ti.f32);
N = 128

@ti.layout
def place():
  ti.root.dense(ti.ij, [N,N]).dense(ti.ij, [8,8]).place(a)

@ti.kernel
def set1():
  for i,j in a:
    a[i,j] = 2.0

@ti.kernel
def set2():
  for j in range(N*8):
    for i in range(N*8):
      a[i,j] = 2.0

set1()
set2()

t = time.time()
for n in range(1000):
  set1()
elapsed = time.time() - t
print(elapsed)

t = time.time()
for n in range(1000):
  set2()
elapsed = time.time() - t
print(elapsed)
```

**Comment by yuanming-hu** [comment]
Thanks for reporting. This is an interesting observation. I can reproduce this on my remote GPU (which has 300ms+ ping...) There is a GPU page fault when generating the list of blocks, when using the LLVM backend. I'll fix this when I'm back to US.

**Comment by yuanming-hu** [comment]
This due to the list generation of 8x8 blocks was implemented as a serial kernel on GPU, which is really slow. I fixed this issue. Starting from today I'm looking into performance aspects of the new LLVM backend.
