### ISSUE TITLE
Legacy Cuda backend segfaults

### ISSUE THREAD

**Issue by KLozes** [yuanming-hu/taichi#298]
Hi @yuanming-hu,

Ever since you switched to the legacy llvm backend, the legacy Cuda backend has thrown a segfault even on very simple kernels. Can you look into this? I am using this backend for now as it is the most mature for sparse data structures. 

Thanks,
Ken

**Comment by yuanming-hu** [comment]
Hi Ken,

The legacy CUDA backend does not support python frontend. You will have to use the C++14 frontend, like what I did in the tests: https://github.com/yuanming-hu/taichi/tree/master/tests/cpp. Given the limited time I have, the legacy backend will no longer be maintained.

Sorry about the convenience. 

I suggest waiting until the new llvm backend for sparse computation is fully done. I'll start work on that once I'm back to US.

Best,
Yuanming

**Comment by yuanming-hu** [comment]
Since the LLVM backend is mostly up and will be polished in one week or two, the legacy source-to-source backend will not be further maintained.
