### ISSUE TITLE
taichi_core.so: undefined symbol: __cpu_model on Ubuntu 16.04

### ISSUE THREAD

**Issue by janvorac** [yuanming-hu/taichi#33]
Taichi won't import:

```
/home/janvorac/wheel/packages/taichi/taichi/python/taichi/core/load_core.py in <module>()
     29         sys.path.append(bin_dir)
     30         shutil.copy('libtaichi_core.so', 'taichi_core.so')
---> 31         import taichi_core as tc_core
     32 
     33         os.chdir(tmp_cwd)

ImportError: ./taichi_core.so: undefined symbol: __cpu_model
```

Installed using your wiki guide on XUbuntu 16.04.02. I am using Python 2.7.12 in virtual environment downloaded via mkvirtualenv (not compiled on my PC). 
My gcc/g++ version is 5.4.0, cmake version is 3.5.1. Any help would be welcome!

**Comment by yuanming-hu** [comment]
This is really wired. I remember I also compiled Taichi on Ubuntu 16.04 with gcc5 and it worked, though I temporarily don't have access to that machine so I can't double check. Maybe a quick fix here is to compile with `gcc 4`, if you don't want to wait for my latency in fixing it. Sorry that I have several project deadlines... 

If anyone would like to help on this, that greatly appreciated!

**Comment by yuanming-hu** [comment]
This was caused by an update of external/include/stb_image.h in commit https://github.com/yuanming-hu/taichi/commit/259d620736f19b3549d9a318595a437968a3e116, since a bug of `gcc5
` was triggered:
https://bugs.launchpad.net/ubuntu/+source/gcc-5/+bug/1568899

See also,
https://github.com/baldurk/renderdoc/issues/365
https://github.com/nothings/stb/issues/280

**Comment by yuanming-hu** [comment]
As commented in those threads, upgrading to `gcc-6` will probably fix it.

**Comment by yuanming-hu** [comment]
I think it's fixed. Please recompile with gcc-6. Sorry for the delay.

**Comment by yuanming-hu** [comment]
BTW I fixed it by updating stb_image, in the `dev` branch. I'll soon update the master branch.
