### ISSUE TITLE
Issue passing scalar into kernel

### ISSUE THREAD

**Issue by aespielberg** [yuanming-hu/taichi#338]
I'm trying to implement an MLP, with method signature:
```
@ti.data_oriented
class MLP: 

  @ti.classkernel
  def forward(self, obs: ti.f32, s: ti.i32):
    #s is the step number
```

let nn be my instance of this.  I then try to call this method:

```
  obs = scalar_(shape=(2,))
  for i in range(2):
    obs[i] = 0.0
      
  nn.forward(obs, 0)
```
However, whenever I try to do anything with obs, everything breaks.  What is the cause of this?  How do I resolve it?  Is my method signature wrong or something?  My definition of scalar_ is: 

```
def scalar_(shape):
  return ti.var(dt=real, shape=shape)
```

where real is ti.f32.

**Comment by yuanming-hu** [comment]
kernel arguments with ti.f32 take only immediate numbers as inputs. To pass in a tensor, you should use ti.template().

**Comment by aespielberg** [comment]
Thanks, sorry for the dumb question.
