### ISSUE TITLE
Accessing lists in a class from a kernel

### ISSUE THREAD

**Issue by aespielberg** [yuanming-hu/taichi#339]
Let's say I have a classkernel, and in it, I have a ti.static for loop, over a counting variable k, so k is just a regular old python int.

My class has a field, self.li, a list.  In my kernel, I want to access self.li[k], so I can loop over all these integers to use in my kernel.

Unfortunately, self.li[k] is causing an error,

`[E 01/05/20 19:19:59.390] [ir.h:load_if_ptr@2002] ptr.cast<GlobalVariableExpression>()->snode->num_active_indices == 0
[E 01/05/20 19:19:59.390] Received signal 6 (Aborted)`

What is the correct way to do this?

**Comment by yuanming-hu** [comment]
It's probably hard to figure out what happened without code. Could you share with me a piece of sample code to reproduce it?

**Comment by aespielberg** [comment]
Here is my embarrassing MLP class (which will hopefully get better soon), and the code I'm using to call it:

scalar_ code, from math_tools:
```
def scalar_(shape):
  return ti.var(dt=real, shape=shape)
 
``` 


```
import taichi as ti
import IPython
from math_tools import *

@ti.data_oriented
class MLP: 
  
  def __init__(self, num_steps, num_inputs, num_outputs, hidden_layers = (), layer_norm=True, activations=(ti.tanh,)):
    #TOOD: can we automate the use of num_inputs and num_outputs, without having to pass around clunky object references?
    assert len(activations) == len(hidden_layers) + 1 
    
    self.activations = activations
    self.layer_norm = layer_norm
    #TODO: now we need to allocate space for everything
    
    self.sizes = [num_inputs] + [layer for layer in hidden_layers] + [num_outputs]
    
    self.weights = []
    self.biases = []
    self.hiddens = [] #TODO: not sure I actually need to keep track of all these hidden activations
    
    for pair in zip(self.sizes[:-1], self.sizes[1:]):
      self.weights.append(scalar_(shape=pair))
      self.biases.append(scalar_(shape=pair[1:]))
      self.hiddens.append(scalar_(shape=(num_steps, pair[1]))) #note that the last hidden is the final actuation
      
    #TODO: initialize
    

  def get_output(self):
    return self.hiddens[-1]
    
  @ti.classkernel
  def forward(self, obs: ti.template(), s: ti.i32):
    #s is the step number
    
    for k in ti.static(range(len(self.weights))):
      if ti.static(self.layer_norm):
        raise NotImplementedError #TODO
      else:
        in_size = self.sizes[k + 1]
        out_size = self.sizes[k]
        
        for i in range(out_size):
          output = 0.0
          for j in range(in_size):
            input_value = obs[j]
            #if k == 0:
            #  input_value = obs[j]
            #else:              
            #  input_value = self.hiddens[k - 1][j]
            test = self.weights[k]
            print('hi2')
            output += self.weights[k][i, j] * input_value
          
          output += self.biases[k]
          activated_output = self.activations[k](output)
          self.hiddens[k][s, i] = activated_output #the last "hidden" is the output

```          
          
```
Main driver code:

import controllers.mlp as mlp
import taichi as ti
from math_tools import *
#For testing only!         
if __name__ == '__main__':
  @ti.layout
  def place():
    ti.root.lazy_grad()
    
  ti.set_default_fp(ti.f32)
  
  
  nn = mlp.MLP(10, 2, 4, (), False, (ti.tanh,))
  
  #TODO: initialize
  obs = scalar_(shape=(2,))
  for i in range(2):
    obs[i] = 0.0
      
  nn.forward(obs, 0)
  
```

**Comment by yuanming-hu** [comment]
I believe line
```
output += self.biases[k]
```
should be
```
output += self.biases[k][i]
```

This fixes your code. If you don't index `bias` with `[k]` Taichi will assume `bias` is a 0-D tensor (num_active_indices=0), however, it is actually 1-D in your code.

Also please remove `print('hi2')` since Taichi has no string types. Please also remove `test = self.weights[k]` since this statement does nothing, and the semantics is "create a local variable and store self.weight[k] to it", however `self.weight[k]` is a global tensor instead of a local variable.

**Comment by aespielberg** [comment]
Interesting.  The line test = self.weights[k] was actually put in to debug,
but apparently, this breaks things by itself. What is the rule here that I
should keep in mind for the future?

As an aside, but also related to this particular snippet, is there any way
to do if statements on expressions in taichi, inside kernels?  Is this
supported?  Or do I have to break up my kernels to wrap up if statements
around them?

**Comment by yuanming-hu** [comment]
I believe the first question is resolved. For the second question, yes, if statements are supported.
