### ISSUE TITLE
No module named 'taichi_core'

### ISSUE THREAD

**Issue by ganchengyuan1990** [yuanming-hu/taichi#340]
system: macOS

pythonV: Python 3.7.4

**Here is the trace:**
Traceback (most recent call last):
  File "taichi1.py", line 1, in <module>
    import taichi as ti
  File "/Users/ganchengyuan/Desktop/python/python374-env/lib/python3.7/site-packages/taichi/__init__.py", line 1, in <module>
    from taichi.main import main
  File "/Users/ganchengyuan/Desktop/python/python374-env/lib/python3.7/site-packages/taichi/main.py", line 5, in <module>
    from taichi.tools.video import make_video, interpolate_frames
  File "/Users/ganchengyuan/Desktop/python/python374-env/lib/python3.7/site-packages/taichi/tools/video.py", line 3, in <module>
    import taichi.core as core
  File "/Users/ganchengyuan/Desktop/python/python374-env/lib/python3.7/site-packages/taichi/core/__init__.py", line 1, in <module>
    from .util import tc_core, build, format, update, install_package, load_module, start_memory_monitoring
  File "/Users/ganchengyuan/Desktop/python/python374-env/lib/python3.7/site-packages/taichi/core/util.py", line 217, in <module>
    import taichi_core as tc_core
ModuleNotFoundError: No module named 'taichi_core'

Is there anything wrong with my environment?

**Comment by yuanming-hu** [comment]
Hi @ganchengyuan1990 ,

How did you install Taichi?

**Comment by ganchengyuan1990** [comment]
> Hi @ganchengyuan1990 ,
> 
> How did you install Taichi?

Hello, I installed it by "pip install taichi-nightly"

**Comment by yuanming-hu** [comment]
Have you previously installed Taichi before the pip installation?

**Comment by ganchengyuan1990** [comment]
> Have you previously installed Taichi before the pip installation?

no, this is my site-packages.
![image](https://user-images.githubusercontent.com/9605651/71795187-f2c1fa00-307f-11ea-8f6e-aac43f565264.png)

**Comment by yuanming-hu** [comment]
Oh I see the problem. You are installing taichi v0.0.32, which is a very old version. The latest is v0.3.20: https://pypi.org/project/taichi-nightly/#files

**Comment by ganchengyuan1990** [comment]
> Oh I see the problem. You are installing taichi v0.0.32, which is a very old version. The latest is v0.3.20: https://pypi.org/project/taichi-nightly/#files

Cool. you're right. Now I installed v0.3.20. But it stil goes wrong.
By the way. I am using virtualenv.

ImportError: dlopen(/Users/ganchengyuan/Desktop/python/python374-env/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so, 258): Symbol not found: __ZdlPvmSt11align_val_t
  Referenced from: /Users/ganchengyuan/Desktop/python/python374-env/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so
  Expected in: /usr/lib/libc++.1.dylib
 in /Users/ganchengyuan/Desktop/python/python374-env/lib/python3.7/site-packages/taichi/core/../lib/taichi_core.so

**Comment by yuanming-hu** [comment]
Interesting. What's your OS and `ld --version` (if Linux)?

**Comment by ganchengyuan1990** [comment]
> Interesting. What's your OS and `ld --version` (if Linux)?

10.12.6 (16G2136). Maybe my macOS version is too old ?

**Comment by yuanming-hu** [comment]
I guess it's the OS X version - The buildbot is using OS X 10.14. Could you update or find another machine?

**Comment by yuanming-hu** [comment]
OS X 10.15 is not supported either since Travis does not support OS X 10.15...

**Comment by ganchengyuan1990** [comment]
> OS X 10.15 is not supported either since Travis does not support OS X 10.15...

Maybe you're right. I tried it on my linux server. this is the output.
![image](https://user-images.githubusercontent.com/9605651/71798669-fa889b00-308d-11ea-8282-b39fa4fe1811.png)
