### ISSUE TITLE
成书for教材！

### ISSUE THREAD

**Issue by konggujushi** [yuanming-hu/taichi#341]
难能可贵！要是从头开始写成书，即为全国计算机院系提供了高质量的好教材了！

**Comment by tub-sgg** [comment]
support

**Comment by chaunceyjiang** [comment]
support

**Comment by alipay-redpack** [comment]
Github will be a more professional site if reduce or forbid the users that post such as this worthless issue as if they are chatting on the forum .

**Comment by yuanming-hu** [comment]
I think it's a good idea, but I'm closing this issue since it's not really related to the Taichi software.
