### ISSUE TITLE
Issue with "import taichi as ti"

### ISSUE THREAD

**Issue by royalshan** [yuanming-hu/taichi#345]
I tried to download and play around taichi-nightly but ended up with endless bugs of code and can't continue. 

Below is one of the issue I encountered.  This is not the only bug I found. I tried to fix some bugs but thought they are not just bugs. I assume the latest version of  taichi-nightly is updated.

My env: MacOS, python 3.7.4

In [1]: import taichi as ti
[Release mode]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-a49150b41477> in <module>
----> 1 import taichi as ti

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/taichi/__init__.py in <module>
      2 from taichi.core import tc_core as core
      3 from taichi.core import start_memory_monitoring
----> 4 from taichi.dynamics import *
      5 from taichi.geometry import *
      6 from taichi.misc.util import Vector, Vectori

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/taichi/dynamics/__init__.py in <module>
----> 1 from .mpm import MPM
      2 from .simulation import Simulation
      3
      4 __all__ = ['MPM']

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/taichi/dynamics/mpm.py in <module>
      3 from taichi.misc.util import *
      4 from taichi.tools.video import VideoManager
----> 5 from taichi.visual.camera import Camera
      6 from taichi.visual.particle_renderer import ParticleRenderer
      7 from taichi.visual.post_process import LDRDisplay

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/taichi/visual/__init__.py in <module>
      4 from .surface_material import SurfaceMaterial
      5 from .scene import Scene
----> 6 from .mesh import Mesh, create_volumetric_block
      7 from .environment_map import EnvironmentMap
      8 from .texture import Texture

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/taichi/visual/mesh.py in <module>
      1 from taichi.core import tc_core
      2 from taichi.misc.util import *
----> 3 from taichi.scoping.transform_scope import get_current_transform
      4 import taichi
      5

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/taichi/scoping/__init__.py in <module>
----> 1 from .transform_scope import *
      2
      3 __all__ = ['TransformScope', 'transform_scope', 'get_current_transform']

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/taichi/scoping/transform_scope.py in <module>
      1 from taichi.core import tc_core
----> 2 from taichi.tools.transform import Transform
      3 from taichi.misc.util import *
      4 import traceback
      5

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/taichi/tools/transform.py in <module>
      3
      4
----> 5 class Transform:
      6
      7   def __init__(self,

~/.pyenv/versions/3.7.4/lib/python3.7/site-packages/taichi/tools/transform.py in Transform()
      6
      7   def __init__(self,
----> 8                transform=tc_core.Matrix4(1.0),
      9                translate=(0, 0, 0),
     10                rotation=(0, 0, 0),

AttributeError: module 'taichi.core' has no attribute 'Matrix4'

**Comment by yuanming-hu** [comment]
Could you confirm that you are using taichi v0.3.20? Thanks.

**Comment by yuanming-hu** [comment]
`taichi/dynamics/mpm.py` is not a file in any recent release - I guess maybe you have multiple versions of Taichi and they are fighting with each other...

**Comment by royalshan** [comment]
hmm. I checked the version and it is **taichi-nightly   0.0.32**
I am using **python3 -m pip install taichi-nightly** to install but it ends up with 0.0.32 version only. 
Trying to run pip install taichi-nightly==0.3.20 but got below error
_Collecting taichi-nightly==0.3.20
  Could not find a version that satisfies the requirement taichi-nightly==0.3.20 (from versions: 0.0.32)
No matching distribution found for taichi-nightly==0.3.20_

**Comment by yuanming-hu** [comment]
v0.0.32 is a bit too old. Please use v0.3.20: https://pypi.org/project/taichi-nightly/#files
Someone else has reported issues like this, and the cause seems to be CDN caching old versions...
