### ISSUE TITLE
Recursion support?

### ISSUE THREAD

**Issue by hyiltiz** [yuanming-hu/taichi#346]
The documentation specifies that the `taichi` scope *must* happen inside `python` scope, and cannot be nested. It seems to also imply that this scoping also prevents defining recursive taichi functions. Is that so? Is there plans to implement recursion with tail-call optimization built in?

**Comment by yuanming-hu** [comment]
Thanks for the question. Yeah, recursion is not yet implemented. In fact, `@ti.func` are currently forceinlined - supporting **real** function calls may need an IR refactoring... Given forceinlining works well so far, I'd prioritize other stuff other than supporting function calls.
