### ISSUE TITLE
Rendering component of legacy branch

### ISSUE THREAD

**Issue by neverfelly** [yuanming-hu/taichi#348]
Hi author,

Do you have any planning to implement rendering component same as legacy branch of taichi?now it seems to be a hard work to implement various ray tracing algorithm using taichi(maybe it just because i'm not familiar with it)

Thanks

**Comment by yuanming-hu** [comment]
Hi @neverfelly,

Good question. I plan to implement some raytracing examples very soon. They are good for learning the internal mechanism of ray tracers, yet if you want to actually render high-quality images please refer to mature (open-source) renderers such as Mitsuba or pbrt.
