### ISSUE TITLE
纠正一下太极图标

### ISSUE THREAD

**Issue by deerquiet** [yuanming-hu/taichi#349]
太极图应该是这样的：https://dss1.bdstatic.com/70cFvXSh_Q1YnxGkpoWK1HF6hhy/it/u=4253920254,3033918383&fm=26&gp=0.jpg
或者这样的：https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1578425391012&di=f4206b1c99918f49237e3202f939ea2f&imgtype=0&src=http%3A%2F%2Fpic1.zhimg.com%2F99ee370cff03ebda15cc1e0a170a0796_r.jpg
左升右降，左白右黑

**Comment by yuanming-hu** [comment]
Thanks. It's good to know, but I would stick to the current logo design.
